export const deck = [
  {
    src: require('../assets/PNG/blue_back.png'),
    name: 'cover',
    value: 0,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/AD.png'),
    name: 'AceDiamond',
    value: 11,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/AH.png'),
    name: 'AceHeart',
    value: 11,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/AC.png'),
    name: 'AceClub',
    value: 11,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/AS.png'),
    name: 'AceSpade',
    value: 11,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/2D.png'),
    name: 'TwoDiamond',
    value: 2,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/2H.png'),
    name: 'TwoHeart',
    value: 2,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/2C.png'),
    name: 'TwoClub',
    value: 2,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/2S.png'),
    name: 'TwoSpade',
    value: 2,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/3D.png'),
    name: 'ThreeDiamond',
    value: 3,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/3H.png'),
    name: 'ThreeHeart',
    value: 3,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/3C.png'),
    name: 'ThreeClub',
    value: 3,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/3S.png'),
    name: 'ThreeSpade',
    value: 3,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/4D.png'),
    name: 'FourDiamond',
    value: 4,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/4H.png'),
    name: 'FourHeart',
    value: 4,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/4C.png'),
    name: 'FourClub',
    value: 4,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/4S.png'),
    name: 'FourSpade',
    value: 4,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/5D.png'),
    name: 'FiveDiamond',
    value: 5,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/5H.png'),
    name: 'FiveHeart',
    value: 5,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/5C.png'),
    name: 'FiveClub',
    value: 5,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/5S.png'),
    name: 'FiveSpade',
    value: 5,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/6D.png'),
    name: 'SixDiamond',
    value: 6,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/6H.png'),
    name: 'SixHeart',
    value: 6,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/6C.png'),
    name: 'SixClub',
    value: 6,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/6S.png'),
    name: 'SixSpade',
    value: 6,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/7D.png'),
    name: 'SevenDiamond',
    value: 7,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/7H.png'),
    name: 'SevenHeart',
    value: 7,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/7C.png'),
    name: 'SevenClub',
    value: 7,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/7S.png'),
    name: 'SevenSpade',
    value: 7,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/8D.png'),
    name: 'EightDiamond',
    value: 8,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/8H.png'),
    name: 'EightHeart',
    value: 8,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/8C.png'),
    name: 'EightClub',
    value: 8,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/8S.png'),
    name: 'EightSpade',
    value: 8,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/9D.png'),
    name: 'NineDiamond',
    value: 9,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/9H.png'),
    name: 'NineHeart',
    value: 9,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/9C.png'),
    name: 'NineClub',
    value: 9,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/9S.png'),
    name: 'NineSpade',
    value: 9,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/10D.png'),
    name: 'TenDiamond',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/10H.png'),
    name: 'TenHeart',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/10C.png'),
    name: 'TenClub',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/10S.png'),
    name: 'TenSpade',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/JD.png'),
    name: 'JackDiamond',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/JH.png'),
    name: 'JackHeart',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/JC.png'),
    name: 'JackClub',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/JS.png'),
    name: 'JackSpade',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/QD.png'),
    name: 'QueenDiamond',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/QH.png'),
    name: 'QueenHeart',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/QC.png'),
    name: 'QueenClub',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/QS.png'),
    name: 'QueenSpade',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/KD.png'),
    name: 'KingDiamond',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/KH.png'),
    name: 'KingHeart',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets/PNG/KC.png'),
    name: 'KingClub',
    value: 10,
    inPlay: false,
  },
  {
    src: require('../assets//PNG/KS.png'),
    name: 'KingSpade',
    value: 10,
    inPlay: false,
  },
];
